#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <mic_check_icons.h>

int32_t mic_check_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm mic_check!");

    return 0;
}
